env:
  NODE_ENV: staging

envSecrets:
  MONGODB_URI: open-finance-consent
  OPENFINANCE_DB_NAME: open-finance-consent
  LEAFYBANK_DB_NAME: open-finance-consent
  VOYAGE_API_KEY: open-finance-consent

serviceAccount:
  enabled: true
  irsa:
    accountId: "275662791714"
    roleName: "kanopy-staging-cicd-irsa"
