"""
Encrypted MongoDB connection for Queryable Encryption.

Supports two KMS providers:
  - "aws" (production/Kanopy) — uses AWS KMS via IRSA, no local key needed
  - "local" (dev fallback) — reads master-key.bin from disk

Set KMS_PROVIDER=aws and AWS_KMS_KEY_ARN in environment for production.
"""

import os
from pathlib import Path

from bson import json_util
from pymongo import MongoClient
from pymongo.encryption_options import AutoEncryptionOpts

from database.connection import MongoDBConnection


class EncryptedMongoDBConnection(MongoDBConnection):
    """MongoDBConnection backed by an encrypted MongoClient.

    Behaves identically to MongoDBConnection for non-encrypted collections.
    Collections listed in the encrypted_fields_map get automatic
    encryption/decryption via the PyMongo driver.
    """

    def __init__(self, uri: str, auto_encryption_opts: AutoEncryptionOpts):
        self.uri = uri
        try:
            self.client = MongoClient(self.uri, auto_encryption_opts=auto_encryption_opts)
        except Exception as e:
            raise Exception("Failed to create encrypted MongoClient: ", e)


def load_encryption_config(config_path: str) -> dict:
    """Load the encryption config (encrypted_fields_map with keyIds) from JSON.

    Uses bson.json_util to deserialize BSON Binary UUIDs that standard json can't handle.

    Args:
        config_path: Path to encryption_config.json (generated by setup script).

    Returns:
        dict with keys: key_vault_namespace, encrypted_fields_map
    """
    with open(config_path) as f:
        raw = f.read()
    return json_util.loads(raw)


def _build_kms_providers() -> dict:
    """Build KMS providers based on environment.

    KMS_PROVIDER=aws  → AWS KMS (Kanopy/production). Credentials auto-discovered
                        via IRSA (pymongo-auth-aws handles STS AssumeRoleWithWebIdentity).
    KMS_PROVIDER=local (default) → Local 96-byte master key file for dev.
    """
    provider = os.getenv("KMS_PROVIDER", "local")

    if provider == "aws":
        # pymongo-auth-aws auto-discovers credentials from:
        # 1. AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY env vars
        # 2. IRSA (EKS service account token) — used on Kanopy
        # 3. EC2 instance metadata
        return {"aws": {}}

    # Local fallback for development
    master_key_path = os.getenv(
        "LOCAL_MASTER_KEY_PATH",
        str(Path(__file__).resolve().parent.parent / "master-key.bin"),
    )
    master_key = Path(master_key_path).read_bytes()
    return {"local": {"key": master_key}}


def create_encrypted_connection(uri: str, config: dict) -> EncryptedMongoDBConnection:
    """Create an EncryptedMongoDBConnection from URI and encryption config.

    Args:
        uri: MongoDB connection string.
        config: Dict from load_encryption_config() containing
                key_vault_namespace and encrypted_fields_map.

    Returns:
        EncryptedMongoDBConnection ready for use.
    """
    kms_providers = _build_kms_providers()

    # crypt_shared lib path — configurable for Docker (Linux uses .so)
    crypt_shared_lib_path = os.getenv(
        "CRYPT_SHARED_LIB_PATH",
        str(Path(__file__).resolve().parent.parent / "lib" / "mongo_crypt_v1.dylib"),
    )

    auto_opts = AutoEncryptionOpts(
        kms_providers,
        config["key_vault_namespace"],
        encrypted_fields_map=config["encrypted_fields_map"],
        crypt_shared_lib_path=crypt_shared_lib_path,
        crypt_shared_lib_required=True,
    )

    return EncryptedMongoDBConnection(uri, auto_opts)
