"""
Encrypted MongoDB connection for Queryable Encryption.

Provides an EncryptedMongoDBConnection that subclasses MongoDBConnection,
wrapping a MongoClient configured with AutoEncryptionOpts. All existing
services that accept MongoDBConnection work transparently — the driver
handles encryption/decryption automatically for mapped collections.
"""

import os
from pathlib import Path

from bson import json_util
from pymongo import MongoClient
from pymongo.encryption_options import AutoEncryptionOpts

from database.connection import MongoDBConnection


class EncryptedMongoDBConnection(MongoDBConnection):
    """MongoDBConnection backed by an encrypted MongoClient.

    Behaves identically to MongoDBConnection for non-encrypted collections.
    Collections listed in the encrypted_fields_map get automatic
    encryption/decryption via the PyMongo driver.
    """

    def __init__(self, uri: str, auto_encryption_opts: AutoEncryptionOpts):
        self.uri = uri
        try:
            self.client = MongoClient(self.uri, auto_encryption_opts=auto_encryption_opts)
        except Exception as e:
            raise Exception("Failed to create encrypted MongoClient: ", e)


def load_encryption_config(config_path: str) -> dict:
    """Load the encryption config (encrypted_fields_map with keyIds) from JSON.

    Uses bson.json_util to deserialize BSON Binary UUIDs that standard json can't handle.

    Args:
        config_path: Path to encryption_config.json (generated by setup script).

    Returns:
        dict with keys: key_vault_namespace, encrypted_fields_map
    """
    with open(config_path) as f:
        raw = f.read()
    return json_util.loads(raw)


def create_encrypted_connection(uri: str, config: dict) -> EncryptedMongoDBConnection:
    """Create an EncryptedMongoDBConnection from URI and encryption config.

    Args:
        uri: MongoDB connection string.
        config: Dict from load_encryption_config() containing
                key_vault_namespace and encrypted_fields_map.

    Returns:
        EncryptedMongoDBConnection ready for use.
    """
    # Load master key
    master_key_path = os.getenv(
        "LOCAL_MASTER_KEY_PATH",
        str(Path(__file__).resolve().parent.parent / "master-key.bin"),
    )
    master_key = Path(master_key_path).read_bytes()
    kms_providers = {"local": {"key": master_key}}

    # crypt_shared lib path — configurable for Docker (Linux uses .so)
    crypt_shared_lib_path = os.getenv(
        "CRYPT_SHARED_LIB_PATH",
        str(Path(__file__).resolve().parent.parent / "lib" / "mongo_crypt_v1.dylib"),
    )

    auto_opts = AutoEncryptionOpts(
        kms_providers,
        config["key_vault_namespace"],
        encrypted_fields_map=config["encrypted_fields_map"],
        crypt_shared_lib_path=crypt_shared_lib_path,
    )

    return EncryptedMongoDBConnection(uri, auto_opts)
